package main

import (
	"context"
	"fmt"
	"time"
)

func (s *Store) GetQARunReport(ctx context.Context, id string) (*QARunReport, error) {
	run, err := s.GetQARun(ctx, id)
	if err != nil {
		return nil, err
	}
	project, err := s.GetProject(ctx, run.ProjectID)
	if err != nil {
		return nil, err
	}

	var discoveryRun *DiscoveryRun
	var discoverySummary *DiscoverySummary
	findings := []Finding{}
	evidence := []Evidence{}
	if run.DiscoveryRunID != "" {
		discoveryReport, err := s.GetDiscoveryReport(ctx, run.DiscoveryRunID)
		if err != nil {
			return nil, err
		}
		discoveryRun = &discoveryReport.Run
		discoverySummary = &discoveryReport.Summary
		findings = append(findings, discoveryReport.Findings...)
		evidence = append(evidence, discoveryReport.Evidence...)
	}

	var qualityRun *QualityCheckRun
	var qualitySummary *QualityCheckSummary
	qualityResults := []QualityCheckResult{}
	if run.QualityCheckRunID != "" {
		qualityReport, err := s.GetQualityCheckReport(ctx, run.QualityCheckRunID)
		if err != nil {
			return nil, err
		}
		qualityRun = &qualityReport.Run
		qualitySummary = &qualityReport.Summary
		qualityResults = qualityReport.Results
		findings = append(findings, qualityReport.Findings...)
	}

	var plan *TestPlan
	var preview *TestPlanExecutionPreview
	if run.TestPlanID != "" {
		plan, err = s.GetTestPlan(ctx, run.TestPlanID)
		if err != nil {
			return nil, err
		}
		preview, _ = BuildTestPlanExecutionPreview(*plan, *project, TestPlanExecutionRequest{
			DryRun:       true,
			MaxScenarios: summaryInt(run.Summary, "max_scenarios", defaultMaxTestPlanScenarios),
		})
	}

	var executionReport *TestPlanExecutionReport
	if run.TestPlanExecutionID != "" {
		executionReport, err = s.GetTestPlanExecutionReport(ctx, run.TestPlanExecutionID)
		if err != nil {
			return nil, err
		}
		findings = append(findings, executionReport.Findings...)
		evidence = append(evidence, executionReport.Evidence...)
	}

	report := &QARunReport{
		Run:              *run,
		Project:          *project,
		DiscoveryRun:     discoveryRun,
		DiscoverySummary: discoverySummary,
		QualityCheckRun:  qualityRun,
		QualitySummary:   qualitySummary,
		QualityResults:   qualityResults,
		TestPlan:         plan,
		ExecutionPreview: preview,
		ExecutionReport:  executionReport,
		Findings:         findings,
		Evidence:         evidence,
		SafetyNotes:      qaRunSafetyNotes(),
		Limitations:      qaRunLimitations(),
		GeneratedAt:      time.Now().UTC(),
	}
	report.ReportIntelligence = BuildReportIntelligence(ReportIntelligenceInput{
		ReportType:        "safe_qa_run",
		ReportID:          run.ID,
		Status:            run.Status,
		Project:           project,
		Findings:          findings,
		Evidence:          evidence,
		ChecksCompleted:   qaRunCompletedChecks(report),
		ChecksSkipped:     qaRunSkippedChecks(report),
		WhatWasTested:     []string{"Application discovery", "Optional passive quality checks", "AI-assisted test plan generation from sanitized metadata", "Approved safe browser DSL execution when enabled"},
		WhatWasNotTested:  defaultWhatWasNotTested("safe_qa_run"),
		SafetyLimitations: report.Limitations,
	})
	return report, nil
}

func qaRunSafetyNotes() []string {
	return []string{
		"Safe QA runs use deterministic discovery, sanitized AI test generation, and the approved safe browser DSL only.",
		"AI receives sanitized metadata only; credentials, cookies, local storage, session storage, authorization headers, full HTML, screenshots, request bodies, and response bodies are not sent.",
		"Generated plans are previewed and filtered before execution. Unsupported, unsafe, authenticated, destructive, mutating, submit/upload/admin, exploit, and out-of-scope steps are skipped.",
		"Discovery defaults to same-origin navigation and allowed-host enforcement, and does not submit forms or click arbitrary buttons.",
		"Included quality checks are passive, deterministic, metadata-only checks and do not submit forms, fuzz inputs, or run active security payloads.",
	}
}

func qaRunLimitations() []string {
	return []string{
		"Safe QA runs are alpha coverage and are not exhaustive crawling or full regression automation.",
		"Only the supported deterministic browser DSL subset can execute from AI-generated plans.",
		"Authenticated page discovery can use configured credential profiles, but credentials are not sent to AI and login actions are not generated by AI.",
		"API smoke, authorization checks, and browser smoke remain separate flows; this QA run focuses on discovery-aware browser plan generation and safe plan execution.",
		"Quality checks are alpha heuristics for obvious passive security, accessibility, and performance issues, not a full audit.",
	}
}

func qaRunHTMLTitle(report *QARunReport) string {
	if report == nil {
		return "Qualora safe QA report"
	}
	return fmt.Sprintf("Qualora safe QA report - %s", report.Project.Name)
}
